### ISSUE TITLE
crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by cozzbie** [juliangruber/keypair#12]
This just started happening when run in a browser it throws

`crypto.randomBytes is not a function` and I am not exactly sure how to circumvent this.

**Comment by juliangruber** [comment]
what are you using to bundle this for the browser?

**Comment by cozzbie** [comment]
Webpack. Running in ionic 2 v 2.3.0

**Comment by juliangruber** [comment]
I haven't used Webpack before, but `crypto` is a node core module that webpack needs to bundle as well. Since it works with browserify though, I'm closing as won't fix and encourage you to ask webpack people how to do this.

**Comment by cozzbie** [comment]
Gracias.

**Comment by cozzbie** [comment]
So I just found out that this only occurs in Safari (Version 10.1 (12603.1.30.0.34)) and iOS webkit too but works fine on Chrome.

**Comment by cozzbie** [comment]
Is there anything or any advice you can give on this. WebWorkers in Safari do not have access to the Crypto API and thus it throws that error.

**Comment by juliangruber** [comment]
maybe try this module by @mafintosh instead: https://github.com/mafintosh/sodium-signatures

```js
var signatures = require('sodium-signatures')
var keys = signatures.keyPair()
console.log(keys)
```

**Comment by cozzbie** [comment]
Seemed  like overkill to me so I simply compiled a node crypto js file with webpack and used importScripts to force it into the global space of WebWorker for Safari. Thanks.

**Comment by juliangruber** [comment]
haha that's awesome!
