### ISSUE TITLE
How to use it client-side?

### ISSUE THREAD

**Issue by josephernest** [juliangruber/keypair#14]
I'd like to use `keypair`  client-side. I tried creating `index.html` with:

```
<script type="text/javascript" src="keypair.js"></script>
<script type="text/javascript">
var pair = keypair();
console.log(pair);
</script>
```

but it doesn't  work:

    Uncaught ReferenceError: module is not defined
    Uncaught ReferenceError: keypair is not defined

How to make it available from browser?

**Comment by juliangruber** [comment]
It is designed to be consumed by a bundler like browserify or webpack, however you can also create a standalone build like this:

```bash
npm install --global browserify
browserify --standalone keypair.js --outfile keypair.bundle.js
```

Then include the `keypair.bundle.js` in your html and you get the global `keypair()` variable.

**Comment by josephernest** [comment]
Here is what I tried:

```
npm install --global browserify            # success here
wget https://raw.githubusercontent.com/juliangruber/keypair/master/index.js     # success
browserify --standalone index.js --outfile keypair.bundle.js        # success, no error message

```

Here's the result:

    (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({},{},[])

Maybe it could be interesting to add a note in the README.md for people who want to use it client-side as a JS to include in a HTML, without any knowledge about npm.

**Comment by juliangruber** [comment]
Sorry, that's the correct command:

```bash
$ browserify --standalone=keypair index.js --outfile keypair.bundle.js
```

I'll add a note to the README

**Comment by josephernest** [comment]
Thanks!
