### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by bahamas10** [juliangruber/keypair#4]
`package.json` says MIT, README says BSD, LICENSE file says BSD or GPL.

**Comment by bruce965** [comment]
NPM repository still reports this package to be under MIT license.

https://www.npmjs.com/package/keypair

**Comment by juliangruber** [comment]
true! published with updated license as 1.0.1

**Comment by bruce965** [comment]
Thanks, I think any ambiguity is solved now. Unfortunately it looks some of this package's 	
dependents published their under MIT license.
