### ISSUE TITLE
Use with authorized_keys

### ISSUE THREAD

**Issue by benjick** [juliangruber/keypair#6]
Hi

Would it be possible to use this lib with authorized_keys on Linux?

Reading http://askubuntu.com/questions/46424/adding-ssh-keys-to-authorized-keys it says

> This public key has the .pub extension when generated using ssh-keygen and its contents begin with ssh-rsa AAAAB3. 

All my pubkeys generated with `keypair` starts with `MIIEp`. Would this be a problem?

**Comment by juliangruber** [comment]
@mikeal i think you dealt with this?

**Comment by mikeal** [comment]
ya, i kinda forgot how i did it though and can't seem to find that code anywhere :)

**Comment by maxogden** [comment]
you can do it like this:

```js
var keypair = require('keypair')
var forge = require('node-forge')

var pair = keypair()
var publicKey = forge.pki.publicKeyFromPem(pair.public)
var ssh = forge.ssh.publicKeyToOpenSSH(publicKey, 'user@domain.tld')
console.log(ssh)
```

**Comment by juliangruber** [comment]
awesome max! added to docs in #f7f6ff2

**Comment by benjick** [comment]
Thanks :)
