### ISSUE TITLE
How can I generate SSH2 public key?

### ISSUE THREAD

**Issue by soichih** [juliangruber/keypair#9]
Can I use the generate keys for ssh2? I am guessing.. I can use the private key just fine, but I need to convert the public key into ssh2 (with ---- BEGIN SSH2 PUBLIC KEY ----) format so that I can put them under ~/.ssh/authorized_keys before I can connect using ssh2 npm module?

**Comment by juliangruber** [comment]
try this snippet https://github.com/juliangruber/keypair/pull/8/files#diff-168726dbe96b3ce427e7fedce31bb0bcR28

**Comment by soichih** [comment]
Thanks!

I decided to use node-rsa to generate the key and convert to ssh2 format with ursa-purejs. Thanks anyway!
